mikaoj/BSImagePicker

- Pod/Classes/Extension/UIButton+NoAnimation.swift
Issue #78. 
Animation error in popover when animations are disabled. After taking a photo the popover was showing a animation.
> Fixed UIButton extension when animation are disabled

- Pod/Classes/Model/CameraCollectionViewDataSource.swift
- Pod/Classes/Model/PhotoCollectionViewDataSource.swift
In the tradition of offering a fix rather than only reporting an issue:
Currently, the BSImagePicker camera and photo cells don't have accessibility identifiers, which makes it problematic to build XCUITests that use them. This PR adds said accessIDs, so that one can call e.g. `app.cells["photo_cell_2"].tap()` in the XCUITest framework.
> Added accessibility identifiers to cells for XCUITest compatibility

- Pod/Classes/Controller/BSImagePickerViewController.swift
It seems that there is a bug with the swift compiler header generation. Changing the access control of these variables to private seems to fix the issue.
See: https://forums.developer.apple.com/thread/63156
> Fixed a problem with swift’s header generation

- Pod/Classes/Controller/PhotosViewController.swift
On iOS 10, in our project, a layout update of the navigation bar is required for ensuring the selection/done button has the correct layout. Before adding the line we were seeing this glitch:
> [iOS 10] Trigger Relayout of Navigation Bar When Changing Button

- Pod/Classes/Controller/BSImagePickerViewController.swift
I changed the access modifier of the fetchResults property from private to open. The documentation mentions using this property in the Custom Fetch Results section.
> Changed access modifier of fetchResults

- Source/Controller/PhotosViewController.swift
- Source/Extension/UIViewController+BSImagePicker.swift
- Source/Model/PhotoCollectionViewDataSource.swift
We use this at PlanGrid, and we've been meaning to get back to using the original project (i.e. not our own fork) for some time. This contributes back the 2 pieces that we added, which led to us keeping the fork around:
- Adds the `selectLimitReachedClosure`, which is called
when the user attempts select another cell, but the
user has already reached the selection limit
- Marks the `UICollectionViewCell`s as
`isAccessibilityElement = true`, which reduces UI
test flakes/failures
> Add selectLimitReachedClosure & minor UI test fix

- Source/Extension/UIViewController+BSImagePicker.swift
This fixes the public naming of `selectLimitReachedClosure` in `UIViewController+BSImagePicker` to match the naming of the other closure params (no "closure" at the end).
> Fix selectLimitReachedClosure param naming

- .travis.yml
- BSImagePicker.xcodeproj/project.pbxproj
It seems that the dependency between BSImagePicker wasn't correctly
specified as a dependency for the example app. Additionally fixing the .travis.yml that causes CI to fail.
> Fix the issue with building the example app for a device

- Sources/Model/AlbumTableViewDataSource.swift
- Sources/Model/PhotoCollectionViewDataSource.swift
- Sources/View/AlbumCell.swift
Prior to this change the images extracted from PHImageManager didn't
accoutn for the device scale. This change ensures that the images are
extracted based on the user's device.
Reference:
https://stackoverflow.com/questions/31752527/does-phimagemanager-return-images-in-pixel-or-point-size-for-2x-and-3x-screens/36453340
> Fix photo scale issue in photo and album views

- Sources/Controller/ImagePickerController.swift
Make `ImagePickerController` class open to enable sub-classing and further customizations, while `public` classes cannot be inherited in Swift.
> Make `ImagePickerController` class open

- Example/ViewController.swift
- Sources/Controller/ImagePickerController.swift
- patch to enable preselected assets again
- don't require AssetStore being part of API, work with [PHAsset] only
> enable preselected assets

- BSImagePicker.podspec
- Sources/Model/Settings.swift
Hi @mikaoj, sorry, I completely forgot to expose `Settings` members, thus, I wasn't able to access/config them on Obj-C side to properly config my picker, hence, this PR.
Thank you for your comprehension.
> Exposes Settings members to Objective-C

- BSImagePicker.podspec
- Sources/Model/Settings.swift
Hi, here I am again with a new class member that I need to access. It would be great if there was a magically way to expose them all — no, there isn't. Closer we have is the `@objcMembers` 😄
Thanks as always @mikaoj!
> Exposes Album member to Objective-C

- BSImagePicker.xcodeproj/project.pbxproj
- Example/Base.lproj/Main.storyboard
- Sources/Controller/ImagePickerController.swift
- Sources/Extension/UIColor+BSImagePicker.swift
- Sources/Model/Settings.swift
- Sources/Scene/Assets/AssetCollectionViewCell.swift
- Sources/Scene/Assets/VideoCollectionViewCell.swift
- Sources/Scene/Preview/PreviewViewController.swift
- Sources/View/ArrowView.swift
Hi Joakim,
I've added support for dark mode in the app(https://github.com/mikaoj/BSImagePicker/issues/264)
1. I ensured that devices working on iOS 13.0, will work as it is.
2. For iOS 13.0 and more, the basic color will change as per the color modes - dark and light
3. I've added the color extension which we can use it for setting any color in the app for any section. 
Please review and let me know if anything I can improve. 
Thanks
> dark mode support

- BSImagePicker.xcodeproj/project.pbxproj
- Sources/Controller/ImagePickerController+PresentationDelegate.swift
- Sources/Controller/ImagePickerController.swift
- Sources/Model/Settings.swift
This PR adds a new option `Settings.Dismiss.allowSwipe`, which allows the user to close the image picker by swiping down on the screen. I believe this feature is expected by many users in a modern iOS 13 app. I've set the default value of this option to `false` to ensure backwards compatibility.
Thank you for considering my changes! Please feel free to make any edits.
> Allow swipe to dismiss the image picker

- Sources/Presentation/Dropdown/DropdownPresentationController.swift
I've noticed that the album dropdown exceeds the bounds of the presenting sheet on iPad:
I've created a small PR to fix this issue.
> Fixed layout issue with album dropdown on iPad

- Sources/Scene/Assets/AssetsViewController.swift
> FIX attempt to delete and reload the same index path

- Sources/Model/Settings.swift
Xcode show build error when user has 'Settings.swift' same name class.
It is Objc header conflict issue.
also I got error too because my project has 'Settings' Coredata model class.
> Currently BSImagePicker has issues on Xcode 12.

- Sources/Scene/Assets/AssetsCollectionViewDataSource.swift
- Sources/Scene/Assets/AssetsViewController.swift
- Had forgot to set prefetch data source on collection view.
- Removed image size calculation on every cell dequeue.
- Use PHCachingImageManager caching API.
- Clear image cache when changing image size or fetch result.
- Use nil for fetch options as setting it _might_ override some performance optimizations apple has done according to some old SO post.
> Performance optimizations

- Sources/Presentation/Dropdown/DropdownPresentationController.swift
If I set `imagePicker.modalPresentationStyle = .fullScreen`, the position of dropdown `AlbumsViewController` will be wrong.
> Fix dropdown position

- Sources/Scene/Assets/AssetsViewController.swift
Steps to reproduce:
1. Select some photos
2. Go to Photos app to delete photos just selected
3. Back to example app
You will find that the selected photos are gone, but the number displayed on the `doneButton` has not changed. The reason is that the selected assets are not removed from the `store`.
> Fix selected assets are not removed after the corresponding photo is deleted

- Sources/Controller/ImagePickerController.swift
- Sources/Model/Settings.swift
- Sources/Scene/Assets/GradientView.swift
Allows ObjC code to access additional configuration classes and their variables (Selection, List, Fetch, Album, Assets) and improves a few class naming issues when used in ObjC projects (ImagePickerController, GradientView).
Should have zero effect on Swift users.
===================
Tip for ObjC users: ObjC code is unable to access the MediaTypes enum-struct to set supportedMediaTypes. To 
change the default of "images only", you can manually override the fetch predicate like so:
```
BSImagePickerController *bsImagePicker = [[BSImagePickerController alloc] initWithSelectedAssets:@[]];
PHFetchOptions *fetchOptions = bsImagePicker.settings.fetch.assets.options;
// Include both images and video
fetchOptions.predicate = [NSPredicate predicateWithFormat:@"mediaType = %d OR mediaType = %d", …
```
>  Improve Objc access in controller, settings, and gradient view

- Sources/Controller/ImagePickerController.swift
I fixed the localization issue for the Done button in `ImagePickerController` by changing `Bundle(identifier: "com.apple.UIKit")` to `Bundle(for: UIBarButtonItem.self)`.
If you use `Bundle.init(for:)` method, you can get the bundle for a specific class.
Thank you!
> Fix the apple localization for the Done button

- Sources/Model/Settings.swift
- Sources/Presentation/Dropdown/DropdownPresentationController.swift
- Sources/Scene/Albums/AlbumsViewController.swift
I was using this picker on a swiftui project and was asked to add albums to the picker I noticed issue #268
This PR adds: 
- configurable background color to albumviewcontroller based on the theme  
- checks for safe area insets if there is no navigation controller 
In the DropdownPresentationController in swiftUI you can get:
```
type(of: presentingViewController)
> SwiftUI.SheetHostingController
```
And I'm not sure if we can get the underlying navigation bar height. 
However, instead of defaulting to `.zero` respecting safe area insets might be a nicer solution.
> Configurable album overlay background and default starting point for album overlay proposal

- Sources/Controller/ImagePickerController.swift
Swapping the lines makes it work.
So remove asset first and then unselect from assetsViewController
> <FIX>: Indexed number is incorrect when deselecting

- BSImagePicker.podspec
- Package.swift
- Sources/Resources/PrivacyInfo.xcprivacy
#359 
The PR has the following updates: 
* Adding the .xcprivacy file which lists reason for usage of the required reason API's. 
* Updating the swift tool version to 5.7 which gives the ability for SPM to add resource folders
* Updated package.swift file to add privacy file
* Updated podspec to add information about the privacy file. 
Testing: 
Generated a privacy report, Archive the app which consumes the library using SPM, and then in Xcode -> Window -> Organizer -> Under Archives, right click on the archive -> Generate Privacy Report.
> feat: add .xcprivacy file for privacy api's

- Sources/Scene/Assets/AssetsViewController.swift
I experienced an issue "Invalid batch updates detected", when the main thread was busy working. 
The `photoLibraryDidChange` function would be called multiple times on background thread and `changes` fetched by old `fetchResult` caused NSInternalInconsistencyException crash in async main dispatch block.
This change eliminates the possibility that fetched changes will be stale. 😀
> fix NSInternalInconsistencyException crash
